{
	"version": 1502488055,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"background-sheet0.png",
		"play-sheet0.png",
		"reset-sheet0.png",
		"logo-sheet0.png",
		"credit-sheet0.png",
		"player-sheet0.png",
		"deco_bas-sheet0.png",
		"deco_haut-sheet0.png",
		"bulle_1.ogg",
		"bulle_2.ogg",
		"bulle_3.ogg",
		"ah_1.ogg",
		"ah_2.ogg",
		"otest.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}